#Site configuration
title: 简历
name:  Read Jekyll
author: 刘柏
work:  
year: 2018

# Navigation
nav1: "教育背景"
nav2: "工作经历"
nav3: "项目经历"
nav4: "知识技能"
nav5: "自我评价"

# Section1
sec1: "教育背景"
sec2: "南昌大学"
sec3: "信息工程学院–物联网工程"

# Section 2
sec4: "工作经历"
sec5: "用户调研 原型设计 产品设计"
icon1: "fas fa-code"
icont1: "Write all the code"
icon2: "fa-cubes"
icont2: "Stack small boxes"
icon3: "fa-book"
icont3: "Read books and stuff"
icon4: "fa-coffee"
icont4: "Drink much coffee"
icon5: "fa-bolt"
icont5: "Lightning bolt"
icon6: "fa-users"
icont6: "Shadow clone technique"

# Section 3
sec31: "项目背景"
sec32: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer non. Adipiscing cubilia elementum integer. Integer eu ante ornare amet commetus."
sec33: "Possibly broke spacetime"
sec34: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
sec35: "Terraformed a small moon"
sec36: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
sec37: "Snapped dark matter in the wild"
sec38: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."

#section 4
sec41: "知识技能"
sec42: ""
sec43: ""

#section 5
sec51: "自我评价"
sec52: ""
sec53: ""

# Social Links
#facebook: username
#twitter:  username
#google: username
#instagram: username
#pinterest: username
#linkedin: username
#youtube: username
#spotify: username
#lastfm: username
#github: username
#stackoverflow: username
#quora: username
#reddit: username
#medium: username
#vimeo: username
#keybase: username
#email: username

