#Site configuration
title: 简历
name:  Read Jekyll
author: 刘柏
work:  产品
year: 2018
baseurl: "/Read"
# Navigation
nav1: "教育背景"
nav2: "工作经历"
nav3: "项目经历"
nav4: "知识技能"
nav5: "自我评价"

# Section1
sec1: "教育背景"
sec2: "南昌大学"
sec22: "2013.9-2017.5"
sec3: "信息工程学院"
sec14: "物联网工程(本科)"

# Section 2
sec4: "工作经历"
sec5: "郑州格物至微科技有限公司"
icon1: "fa-product-hunt"
icont1: "产品经理"




# Section 3
sec31: "项目经历"
sec32: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer non. Adipiscing cubilia elementum integer. Integer eu ante ornare amet commetus."
sec33: "用户调研 原型设计 产品设计"
sec34: "<b>目标：</b> 获取用户需求。 <b>行动：</b> 蹲点观察中原区23个楼盘的销售流程，并随机采访13个楼盘的销售经理了解需求。独立完成数据分析并形成用户需求分析报告。 <b>结果：</b> 60%的用户需求最终转化为实际项目（6/10）。<br /><b>目标： </b>按需求完成系统交互原型 <b>合作：</b> 与UI设计师合作完成预览图。 <b>行动：</b> 基于用户调研的结果，使用balsamiq完成系统功能的原型设计，与UI设计师合作完成预览图，输出PRD文档（30页，10112字）。 <b>结果：</b> PRD在规定时间内通过评审。"
sec35: "产品调研 用户调研 竞品分析"
sec36: "<b>目标：</b> 前期市场调查。 <b>行动：</b> 基于公安部交管局、《德勒2017年中国交强险市场分析报告》公布的数据得到目标客户（客车、卡车）市场保有量和年销量，独立分析数据，估算市场体量，并对竞品（G7、伊路安行等）从产品形式、目标客户、销售策略等方式进行分析，完成市场调查。 <b>结果：</b> 市场调查一次通过评审。<br /><b>目标：</b> 获取用户需求。 <b>合作：</b> 与4人合作，在规定时间内完成市场调查。 <b>行动：</b> 对301国道附近8个物流园，共46家物流公司进行上门拜访，与其中19家公司的业务负责人沟通需求，完成数据分析并形成需求分析报告。 <b>结果：</b> 71.43%的用户需求被转化为实际项目（10/14）。"
sec37: "用户沟通 成本估算 方案设计"
sec38: "<b>目标：</b> 获取甲方需求。 <b>行动：</b> 约见甲方，了解应用场景以及现有流程，确定产品在对方工作流程中所处的环节以及作用，深入了解甲方需求，完成需求文档初稿。<b>结果：</b> 与技术人员沟通，将占用人力较多的功能标注，再次回访甲方。<br /><b>目标：</b> 提交项目方案。<b>合作：</b> 与技术总监沟通，确定开发周期与人力成本，并对项目中可能发生的问题做预估。 <b>行动：</b> 根据甲方实际需求绘制系统框架图、流程图、界面原型，输出项目方案（31页，8164字）。 <b>结果：</b> 方案在规定期限内完成，并受到甲方好评。"

#section 4
sec41: "知识技能"
icon41: "fa-lightbulb-o"
icont41: "<b>Mindmanage</b>思维导图工具"
icon42: "fa-cube"
icont42: "<b>Balsamiq</b>产品原型工具"
icon43: "fa-cubes"
icont43: "<b>Axure</b>产品原型软件"
icon44: "fa-line-chart"
icont44: "<b>Python编程/数据分析</b>"

#section 5
sec51: "自我评价"
sec52: "<b>喜欢学习 </b>对新知识充满好奇，工作期间自学完成廖雪峰 <b>Python </b>教程、谷歌机器学习平台 <b>TensorFlow </b>教程。对 <b>区块链 </b>有一定认识，阅读过《京东区块链技术实践白皮书-2018.3》，《腾讯区块链方案白皮书》，重点关注新技术的落地和商业模式的构建。"
sec53: "<b>喜欢新事物 </b>极客爱好者，动手能力强。树莓派第一批玩家，大学期间为了解前沿黑科技，独立架设vps。积极尝试新鲜事物，从使用者的角度体会产品人的用心，注重互联网+时代人与人连接的场景，不断巩固和提高产品思维。"
sec54: "<b>喜欢APP </b>除国内主流APP外，对Twitter、Telegram、SoundCloud等国外APP也有所涉猎。 <b>GTD </b>轻度使用者(1年)，Things3、时间块、OneNote、Dropbox深度使用者，善于使用APP提升工作效率。 "


# Social Links
#facebook: username
#twitter:  username
#google: username
#instagram: username
#pinterest: username
#linkedin: username
#youtube: username
#spotify: username
#lastfm: username
#github: username
#stackoverflow: username
#quora: username
#reddit: username
#medium: username
#vimeo: username
#keybase: username
email: username 
