#Site configuration
title: 简历
name:  Read Jekyll
author: 刘柏
work:  产品
year: 2018
baseurl: "/Read"
# Navigation
nav1: "教育背景"
nav2: "工作经历"
nav3: "项目经历"
nav4: "知识技能"
nav5: "自我评价"

# Section1
sec1: "教育背景"
sec2: "南昌大学"
sec22: "2013.9-2017.5"
sec3: "信息工程学院物联网工程"
sec14: "物联网工程(本科)"

# Section 2
sec4: "工作经历"
sec5: "郑州格物至微科技有限公司"
icon1: "fa-product-hunt"
icont1: "产品经理"




# Section 3
sec31: "项目经历"
sec32: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer non. Adipiscing cubilia elementum integer. Integer eu ante ornare amet commetus."
sec33: "用户调研 原型设计 产品设计"
sec34: "目标： 获取用户需求。行动： 蹲点观察中原区23个楼盘的销售流程，并随机采访13个楼盘的销售经理了解需求。独立完成数据分析并形成用户需求分析报告。 结果： 60%的用户需求最终转化为实际项目（6/10）。"
sec341: "目标： 按需求完成系统交互原型 合作： 与UI设计师合作完成预览图 行动： 基于用户调研的结果，使用balsamiq完成系统功能的原型设计，与UI设计师合作完成预览图，输出PRD文档（30页，10112字）。 结果： PRD在规定时间内通过评审。"
sec35: "产品调研 用户调研 竞品分析"
sec36: "目标： 前期市场调查 行动： 基于公安部交管局、《德勒2017年中国交强险市场分析报告》公布的数据得到目标客户（客车、卡车）市场保有量和年销量，独立分析数据，估算市场体量，并对竞品（G7、伊路安行等）从产品形式、目标客户、销售策略等方式进行分析，完成市场调查。 结果： 市场调查一次通过评审。"
sec361: "目标： 获取用户需求 合作： 与4人合作，在规定时间内完成市场调查 行动： 对301国道附近8个物流园，共46家物流公司进行上门拜访，与其中19家公司的业务负责人沟通需求，完成数据分析并形成需求分析报告。 结果： 71.43%的用户需求被转化为实际项目（10/14）。"
sec37: "用户沟通 成本估算 方案设计"
sec38: "目标： 获取甲方需求。 行动： 约见甲方，了解应用场景以及现有流程，确定产品在对方工作流程中所处的环节以及作用，深入了解甲方需求，完成需求文档初稿 结果： 与技术人员沟通，将占用人力较多的功能标注，再次回访甲方。目标： 提交项目方案。 合作： 与技术总监沟通，确定开发周期与人力成本，并对项目中可能发生的问题做预估。 行动： 根据甲方实际需求绘制系统框架图、流程图、界面原型，输出项目方案（31页，8164字）。 结果： 方案在规定期限内完成，并受到甲方好评。"

#section 4
sec41: "知识技能"
sec42: ""
sec43: ""

#section 5
sec51: "自我评价"
sec52: ""
sec53: ""

# Social Links
#facebook: username
#twitter:  username
#google: username
#instagram: username
#pinterest: username
#linkedin: username
#youtube: username
#spotify: username
#lastfm: username
#github: username
#stackoverflow: username
#quora: username
#reddit: username
#medium: username
#vimeo: username
#keybase: username
#email: username

